version: "3.7"
services:
  minecraft:
    image: bmoorman/minecraft:latest
    container_name: minecraft
    restart: unless-stopped
    ports:
      - "25569:25565"
    environment:
      MC_EULA: "true"
      MC_ONLINE_MODE: "false"

    volumes:
      - .\minecraft-data:/var/lib/minecraft

volumes:
  minecraft-data: